name: template
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: any
  autocomplete_textfield: ^1.7.3
  json_annotation: any
  font_awesome_flutter: ^8.8.1
  connectivity: 0.4.5+3
  bloc: any
  flutter_bloc: any
  intl: any
  equatable: any
  popup_menu: ^1.0.5
  smart_select: ^4.3.2
  auto_size_text: ^2.1.0
  zefyr: ^0.10.0
  flutter_slidable: ^0.5.7
  flutter_typeahead: ^1.8.0
  month_picker_dialog: ^0.3.2
  flutter_calendar_carousel: ^1.4.12
  flutter_offline: "^0.3.0"
  date_time_picker: "^1.1.1"
  path_provider:
  shared_preferences: any
  url_launcher: any
  avatar_glow:
  flutter_login: ^1.0.10+1
  table_calendar: ^2.2.3
  cupertino_stepper: ^0.1.2
  cupertino_icons: ^1.0.0
  syncfusion_flutter_calendar: ^18.2.46+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any
  flutter_html: ^0.11.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo_ar.png
    - lib/assets/logo.png
    - lib/assets/identety.png
    - lib/Langs/ar.json
    - lib/Langs/en.json

